#!/usr/bin/env bash
# Auto-generated by setup/make_persistent.sh
# Starts the Amblyopia Care System after reboot
set -uo pipefail

PROJECT="/home/anandhu/projects/amblyopia_backend"
LOG_DIR="$PROJECT/logs"
mkdir -p "$LOG_DIR"

log() { echo "$(date '+%Y-%m-%d %H:%M:%S')  $*" | tee -a "$LOG_DIR/startup.log"; }

log "=== Amblyopia Care System Starting ==="
cd "$PROJECT"

# ── Wait for PostgreSQL ─────────────────────────────────────────────────────
log "Waiting for PostgreSQL..."
for i in $(seq 1 30); do
    if pg_isready -q 2>/dev/null; then
        log "PostgreSQL ready"
        break
    fi
    sleep 1
done

# ── Wait for Redis ──────────────────────────────────────────────────────────
log "Waiting for Redis..."
for i in $(seq 1 15); do
    if redis-cli ping 2>/dev/null | grep -q PONG; then
        log "Redis ready"
        break
    fi
    sleep 1
done

# ── Activate virtualenv ─────────────────────────────────────────────────────
log "Activating virtual environment..."
source "$PROJECT/venv/bin/activate"

# ── Run migrations ──────────────────────────────────────────────────────────
log "Running database migrations..."
PYTHONPATH="$PROJECT" alembic upgrade head >> "$LOG_DIR/migrations.log" 2>&1 &&     log "Migrations complete" ||     log "Migration warning — check $LOG_DIR/migrations.log"

# ── Start FastAPI ────────────────────────────────────────────────────────────
log "Starting FastAPI on http://0.0.0.0:8000 ..."
log "API docs: http://localhost:8000/docs"
log "Health:   http://localhost:8000/health"

exec uvicorn app.main:app     --host 0.0.0.0     --port 8000     --workers 1     --log-level info
