"""create_all_14_tables

Revision ID: e908a21c9ade
Revises: 
Create Date: 2026-02-22 05:54:31.662021+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e908a21c9ade'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_trail',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ml_models',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('accuracy_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('precision_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('recall_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('f1_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('training_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dataset_size', sa.Integer(), nullable=True),
    sa.Column('new_cases_used', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='training', nullable=True),
    sa.Column('deployed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tflite_file_path', sa.String(length=500), nullable=True),
    sa.Column('model_size_mb', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('nurses',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('assigned_villages', postgresql.ARRAY(sa.UUID()), server_default='{}', nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('device_specs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('performance_score', sa.Numeric(precision=5, scale=2), server_default='0.0', nullable=True),
    sa.Column('total_screenings', sa.Integer(), server_default='0', nullable=True),
    sa.Column('language_preference', sa.String(length=20), server_default='english', nullable=True),
    sa.Column('last_active', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('retraining_jobs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('trigger_type', sa.String(length=20), server_default='scheduled', nullable=True),
    sa.Column('new_data_count', sa.Integer(), nullable=True),
    sa.Column('previous_model_id', sa.UUID(), nullable=True),
    sa.Column('new_model_id', sa.UUID(), nullable=True),
    sa.Column('old_accuracy', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('new_accuracy', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=True),
    sa.Column('approved_auto', sa.Boolean(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['new_model_id'], ['ml_models.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['previous_model_id'], ['ml_models.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_queue',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=False),
    sa.Column('nurse_id', sa.UUID(), nullable=True),
    sa.Column('payload_type', sa.String(length=30), nullable=False),
    sa.Column('payload_encrypted', sa.Text(), nullable=False),
    sa.Column('sync_status', sa.String(length=20), server_default='pending', nullable=True),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('created_offline_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['nurse_id'], ['nurses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('villages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('lat', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('lng', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('last_screened_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('screening_status', sa.String(length=10), server_default='red', nullable=True),
    sa.Column('estimated_population', sa.Integer(), nullable=True),
    sa.Column('children_under_7', sa.Integer(), nullable=True),
    sa.Column('assigned_nurse_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assigned_nurse_id'], ['nurses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patients',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('face_vector', sa.String(), nullable=True),
    sa.Column('age_group', sa.String(length=20), nullable=False),
    sa.Column('village_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_screened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_screenings', sa.Integer(), server_default='0', nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True),
    sa.ForeignKeyConstraint(['village_id'], ['villages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('screening_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('nurse_id', sa.UUID(), nullable=True),
    sa.Column('village_id', sa.UUID(), nullable=True),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gps_lat', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('gps_lng', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('lighting_condition', sa.String(length=20), nullable=True),
    sa.Column('battery_level', sa.Integer(), nullable=True),
    sa.Column('internet_available', sa.Boolean(), nullable=True),
    sa.Column('sync_status', sa.String(length=20), server_default='pending', nullable=True),
    sa.Column('session_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['nurse_id'], ['nurses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['village_id'], ['villages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('combined_results',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('gaze_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('redgreen_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('snellen_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('overall_risk_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('severity_grade', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('referral_needed', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('referral_letter_url', sa.String(length=500), nullable=True),
    sa.Column('qr_code_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['screening_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('gaze_results',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('left_gaze_x', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('left_gaze_y', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('right_gaze_x', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('right_gaze_y', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('left_fixation_stability', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('right_fixation_stability', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('gaze_asymmetry_score', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('left_blink_ratio', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('right_blink_ratio', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('blink_asymmetry', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('left_blink_count', sa.Integer(), nullable=True),
    sa.Column('right_blink_count', sa.Integer(), nullable=True),
    sa.Column('frames_analyzed', sa.Integer(), nullable=True),
    sa.Column('session_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('result', sa.String(length=30), nullable=True),
    sa.Column('needs_doctor_review', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['screening_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('recipient_type', sa.String(length=20), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('message_template', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['screening_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('redgreen_results',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('left_pupil_diameter', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('right_pupil_diameter', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('asymmetry_ratio', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('suppression_flag', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('dominant_eye', sa.String(length=10), nullable=True),
    sa.Column('binocular_score', sa.Integer(), nullable=True),
    sa.Column('constriction_speed_left', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('constriction_speed_right', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('constriction_amount_left', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('constriction_amount_right', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('result', sa.String(length=50), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('needs_doctor_review', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['screening_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snellen_results',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('visual_acuity_right', sa.String(length=10), nullable=True),
    sa.Column('visual_acuity_left', sa.String(length=10), nullable=True),
    sa.Column('visual_acuity_both', sa.String(length=10), nullable=True),
    sa.Column('per_letter_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_times', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('hesitation_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('gaze_compliance_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('test_mode', sa.String(length=20), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('needs_doctor_review', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['screening_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doctor_reviews',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('combined_result_id', sa.UUID(), nullable=True),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('doctor_verdict', sa.String(length=100), nullable=True),
    sa.Column('doctor_notes', sa.Text(), nullable=True),
    sa.Column('final_diagnosis', sa.String(length=255), nullable=True),
    sa.Column('treatment_plan', sa.Text(), nullable=True),
    sa.Column('follow_up_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('priority', sa.String(length=20), server_default='normal', nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=True),
    sa.ForeignKeyConstraint(['combined_result_id'], ['combined_results.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['screening_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doctor_reviews')
    op.drop_table('snellen_results')
    op.drop_table('redgreen_results')
    op.drop_table('notification_log')
    op.drop_table('gaze_results')
    op.drop_table('combined_results')
    op.drop_table('screening_sessions')
    op.drop_table('patients')
    op.drop_table('villages')
    op.drop_table('sync_queue')
    op.drop_table('retraining_jobs')
    op.drop_table('nurses')
    op.drop_table('ml_models')
    op.drop_table('audit_trail')
    # ### end Alembic commands ###
