#!/usr/bin/env bash
# =============================================================================
# TASK 4 — Make Backend Persistent on Reboot (systemd service)
# Aravind Eye Hospital — Amblyopia Care System
# =============================================================================
set -uo pipefail

PROJECT="/home/anandhu/projects/amblyopia_backend"
USER_NAME="$(whoami)"
SERVICE_NAME="amblyopia"
LOG_DIR="$PROJECT/logs"

echo "================================================"
echo "TASK 4 — Making Backend Persistent on Reboot"
echo "================================================"
echo "User:    $USER_NAME"
echo "Project: $PROJECT"
echo ""

# ── Create log directory ──────────────────────────────────────────────────────
mkdir -p "$LOG_DIR"
echo "Log directory: $LOG_DIR ✓"

# ── Step 1: Enable PostgreSQL and Redis on boot ───────────────────────────────
echo ""
echo "Step 1: Enabling system services..."

# PostgreSQL
if systemctl list-unit-files | grep -q postgresql; then
    sudo systemctl enable postgresql 2>/dev/null && \
        echo "  PostgreSQL: enabled on boot ✓" || \
        echo "  PostgreSQL: enable failed (may need manual setup)"
else
    echo "  PostgreSQL: unit not found — install via apt"
fi

# Redis (service name varies by distro)
REDIS_SVC=""
for svc in redis-server redis; do
    if systemctl list-unit-files | grep -q "^${svc}.service"; then
        REDIS_SVC="$svc"
        break
    fi
done

if [ -n "$REDIS_SVC" ]; then
    sudo systemctl enable "$REDIS_SVC" 2>/dev/null && \
        echo "  Redis ($REDIS_SVC): enabled on boot ✓" || \
        echo "  Redis: enable failed"
else
    echo "  Redis: unit not found — install via apt"
fi

# ── Step 2: Create persistent startup script ───────────────────────────────────
echo ""
echo "Step 2: Creating run_persistent.sh..."

cat > "$PROJECT/run_persistent.sh" << RUNEOF
#!/usr/bin/env bash
# Auto-generated by setup/make_persistent.sh
# Starts the Amblyopia Care System after reboot
set -uo pipefail

PROJECT="$PROJECT"
LOG_DIR="\$PROJECT/logs"
mkdir -p "\$LOG_DIR"

log() { echo "\$(date '+%Y-%m-%d %H:%M:%S')  \$*" | tee -a "\$LOG_DIR/startup.log"; }

log "=== Amblyopia Care System Starting ==="
cd "\$PROJECT"

# ── Wait for PostgreSQL ─────────────────────────────────────────────────────
log "Waiting for PostgreSQL..."
for i in \$(seq 1 30); do
    if pg_isready -q 2>/dev/null; then
        log "PostgreSQL ready"
        break
    fi
    sleep 1
done

# ── Wait for Redis ──────────────────────────────────────────────────────────
log "Waiting for Redis..."
for i in \$(seq 1 15); do
    if redis-cli ping 2>/dev/null | grep -q PONG; then
        log "Redis ready"
        break
    fi
    sleep 1
done

# ── Activate virtualenv ─────────────────────────────────────────────────────
log "Activating virtual environment..."
source "\$PROJECT/venv/bin/activate"

# ── Run migrations ──────────────────────────────────────────────────────────
log "Running database migrations..."
PYTHONPATH="\$PROJECT" alembic upgrade head >> "\$LOG_DIR/migrations.log" 2>&1 && \
    log "Migrations complete" || \
    log "Migration warning — check \$LOG_DIR/migrations.log"

# ── Start FastAPI ────────────────────────────────────────────────────────────
log "Starting FastAPI on http://0.0.0.0:8000 ..."
log "API docs: http://localhost:8000/docs"
log "Health:   http://localhost:8000/health"

exec uvicorn app.main:app \
    --host 0.0.0.0 \
    --port 8000 \
    --workers 1 \
    --log-level info
RUNEOF

chmod +x "$PROJECT/run_persistent.sh"
echo "  $PROJECT/run_persistent.sh ✓"

# ── Step 3: Create systemd service file ───────────────────────────────────────
echo ""
echo "Step 3: Creating systemd service..."

# Determine which Redis service to depend on
REDIS_DEP="redis.service"
if systemctl list-unit-files | grep -q "^redis-server.service"; then
    REDIS_DEP="redis-server.service"
fi

# Resolve venv/bin path for PATH
VENV_BIN="$PROJECT/venv/bin"

sudo tee /etc/systemd/system/${SERVICE_NAME}.service > /dev/null << SVCEOF
[Unit]
Description=Amblyopia Care System – Aravind Eye Hospital, Coimbatore
Documentation=https://github.com/AravindEyeHospital/amblyopia-backend
After=network-online.target postgresql.service ${REDIS_DEP}
Wants=network-online.target postgresql.service ${REDIS_DEP}

[Service]
Type=simple
User=${USER_NAME}
Group=${USER_NAME}
WorkingDirectory=${PROJECT}
ExecStart=/bin/bash ${PROJECT}/run_persistent.sh
Restart=on-failure
RestartSec=15
StartLimitInterval=120
StartLimitBurst=5

# Logging
StandardOutput=append:${LOG_DIR}/backend.log
StandardError=append:${LOG_DIR}/backend_error.log

# Environment
Environment=PYTHONPATH=${PROJECT}
Environment=PATH=${VENV_BIN}:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
Environment=HOME=/home/${USER_NAME}

# Resource limits
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
SVCEOF

echo "  /etc/systemd/system/${SERVICE_NAME}.service ✓"

# ── Step 4: Reload systemd and enable ─────────────────────────────────────────
echo ""
echo "Step 4: Enabling service..."

sudo systemctl daemon-reload
if sudo systemctl enable "${SERVICE_NAME}" 2>/dev/null; then
    echo "  Service '${SERVICE_NAME}' enabled on boot ✓"
else
    echo "  Service enable failed — check sudo permissions"
fi

# ── Step 5: Create log rotation config ────────────────────────────────────────
echo ""
echo "Step 5: Setting up log rotation..."

sudo tee /etc/logrotate.d/amblyopia > /dev/null << LOGEOF
${LOG_DIR}/*.log {
    daily
    rotate 7
    compress
    delaycompress
    missingok
    notifempty
    copytruncate
}
LOGEOF
echo "  Log rotation configured ✓"

# ── Step 6: Create management alias helper ────────────────────────────────────
cat > "$PROJECT/manage.sh" << 'MGEOF'
#!/usr/bin/env bash
# Quick management commands for Amblyopia Care System
SVC="amblyopia"
case "${1:-help}" in
    start)   sudo systemctl start  "$SVC" && echo "Started" ;;
    stop)    sudo systemctl stop   "$SVC" && echo "Stopped" ;;
    restart) sudo systemctl restart "$SVC" && echo "Restarted" ;;
    status)  sudo systemctl status "$SVC" ;;
    logs)    tail -f /home/anandhu/projects/amblyopia_backend/logs/backend.log ;;
    errors)  tail -f /home/anandhu/projects/amblyopia_backend/logs/backend_error.log ;;
    health)  curl -s http://localhost:8000/health | python3 -m json.tool ;;
    *)
        echo "Usage: bash manage.sh [start|stop|restart|status|logs|errors|health]"
        ;;
esac
MGEOF
chmod +x "$PROJECT/manage.sh"
echo "  $PROJECT/manage.sh ✓"

# ── Summary ───────────────────────────────────────────────────────────────────
echo ""
echo "================================================"
echo "PERSISTENCE SETUP COMPLETE"
echo "================================================"
echo ""
echo "  Service name:  ${SERVICE_NAME}"
echo "  Service file:  /etc/systemd/system/${SERVICE_NAME}.service"
echo "  Start script:  ${PROJECT}/run_persistent.sh"
echo "  Log files:     ${LOG_DIR}/"
echo ""
echo "  Management commands:"
echo "    bash manage.sh start    — Start service"
echo "    bash manage.sh stop     — Stop service"
echo "    bash manage.sh status   — Check status"
echo "    bash manage.sh logs     — Follow logs"
echo "    bash manage.sh health   — API health check"
echo ""
echo "  systemctl commands:"
echo "    sudo systemctl start   $SERVICE_NAME"
echo "    sudo systemctl stop    $SERVICE_NAME"
echo "    sudo systemctl status  $SERVICE_NAME"
echo "    sudo systemctl restart $SERVICE_NAME"
echo ""
echo "  Backend automatically starts on next reboot."
echo "================================================"
